CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

CONTIKI = ../../contiki/
include $(CONTIKI)/Makefile.include


clean:
	rm -rf ./obj_z1 ./obj_cooja contiki-z1.a contiki-z1.map hello-world.z1 symbols.c symbols.h
